package com.jojo.springmvc.service.impl;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ${className};
import com.jojo.springmvc.service.${classSimpleName}Service;
import com.jojo.springmvc.service.base.AbstractService;

@Service
@Transactional
public class ${classSimpleName}ServiceImpl extends AbstractService<${classSimpleName}> implements ${classSimpleName}Service {

}
